config/routes.rb
Hex::Application.routes.draw do

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users

  resources :sessions
  resources :games

  root :to => 'games#index'
  match 'games/show/' => 'games#show', :as => 'show_game'
  match 'new', :to => 'games#new'
  match 'games/join/:id' => 'games#join', :as => 'join_game'
  match 'games/move' => 'games#move'

  match 'games/update' => 'games#update'

end

app/models/game.rb
class Game < ActiveRecord::Base
  attr_accessible :horiz_user_id, :vert_user_id

  belongs_to :horiz_user, :class_name => 'User'
  belongs_to :vert_user,  :class_name => 'User'

  def start()
    self.board_state = Hex::Board.create(self.board_width, self.board_height).state
  end

  def players
    [horiz_user, vert_user]
  end

  def move(x, y, color)
    position = (((self.board_width + 1) * Integer(y)) + Integer(x))
    board_copy = self.board_state.clone # Can't seem to edit self.board_state directly.
    board_copy[position] = color        # Making a copy, changing it, and replacing works.
    self.board_state = board_copy
  end

  # def width
  #   board.width
  # end

  # def height
  #   board.height
  # end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :games, :through => :matches

  attr_accessible :email, :guest, :last_signed_in, :password_digest, :username, :password, :password_confirmation

  validates_presence_of :username, :email, :password_digest, unless: :guest?
  validates_uniqueness_of :username, allow_blank: true
  validates_confirmation_of :password, unless: :guest?

  # override has_secure_password to customize validation until Rails 4.
  require 'bcrypt'
  attr_reader :password
  include ActiveModel::SecurePassword::InstanceMethodsOnActivation

  def self.new_guest
    new { |u| u.guest = true }
  end

  def name
    guest ? "Guest#{id}" : username
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    helper_method :current_user

  # after_filter :flash_to_headers

  # def flash_to_headers
  #   return unless request.xhr?
  #   response.headers['X-Message-Type'] = flash_type
  #   response.headers['X-Message'] = flash[:error]  unless flash[:error].blank?
  #   response.headers['X-Message'] = flash[:success]  unless flash[:success].blank?
  #   # repeat for other flash types...

  #   flash.discard  # don't want the flash to appear when you reload page
  # end
end

app/controllers/games_controller.rb
require 'pp'

class GamesController < ApplicationController

  def update
    @game = Game.find(session[:game_id])

    # if @game.current_player_id == @game.horiz_user_id
    #   render :text => "1" # Return who's turn it is to whos_turn() Ajax function
    # else
    #   render :text => "2"
    # end

    render :json => @game
  end

  def move
    @game = Game.find(session[:game_id])
    @game.move(params[:x], params[:y], params[:color])
    @game.last_move_at = DateTime.now

    if @game.current_player_id == @game.horiz_user_id
      @game.current_player_id = @game.vert_user_id
    else
      @game.current_player_id = @game.horiz_user_id
    end
    @game.save

    render :text => "OK"
  end

  def index
    @games = Game.all
  end

  def create
    @game = Game.new(params[:game])
    @game.board_width = params[:dimensions]
    @game.board_height = params[:dimensions]

    user = current_user || User.new_guest
    user.save if user.guest?
    session[:user_id] = user.id

    @game.horiz_user_id = user.id
    @game.current_player_id = user.id
    @game.start()

    #logger.debug "Dimensions: #{params[:dimensions]}"

    respond_to do |format|
      if @game.save
        # flash[:success] = "Game was successfully created."
        format.html  { redirect_to(@game,
                      :notice => 'Game was successfully created.') }
        format.json  { render :json => @game,
                      :status => :created, :location => @game }
      else
        format.html  { render :action => "new" }
        format.json  { render :json => @game.errors,
                      :status => :unprocessable_entity }
      end
      format.js
    end
  end

  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url }
      format.js
    end
  end

  def join
    @game = Game.find(params[:id])
    session[:game_id] = @game.id

    if current_user.nil?
      redirect_to(root_path, :error => 'Could not join game.')
      return
    end    

    if @game.vert_user_id.nil? && @game.horiz_user_id != current_user.id
      @game.vert_user_id = current_user.id
    end

    @game.save

    respond_to do |format|
      format.html { redirect_to :action => "show", :id => @game.id }
    end
  end

  def show
    @game = Game.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = params[:user] ? User.new(params[:user]) : User.new_guest

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def twitterized_type(type)
    case type
      when :success then "alert-success"
      when :alert then "warning"
      when :notice then "info"
      when :error then "alert-error"
      #when :info then "alert-info"
      else
        type.to_s
    end
  end
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/game/new.html.erb
<p id="notice"><%= notice %></p>

<p id="game-top">
  <b>Game:</b>
</p>

<canvas id="hexmap" width="860" height="720"></canvas>

<script>
	initGame(<%= @game.getDimensions[0]  %>, <%= @game.getDimensions[1] %>, false);
</script>

<% if false %>
	<%= link_to 'Edit', edit_session_path(@session) %> |
	<%= link_to 'Back', sessions_path %>
<% end %>

app/views/games/_debug-menu.html.erb
<% if false %>
<div class="debug-menu">
	<div class="btn-toolbar">
	  <div class="btn-group">
	    <button class="btn btn-small btn-info">Testing</button>
	    <button class="btn btn-small btn-info dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></button>
	    <ul class="dropdown-menu">
	      <li><a href="/games/join/<%= @game.id %>/11x11#game-top">11x11 Board size</a></li>
	      <li><a href="/games/join/<%= @game.id %>/13x13#game-top">13x13 Board size</a></li>
	      <li><a href="/games/join/<%= @game.id %>/14x14#game-top">14x14 Board size</a></li>
	      <li><a href="/games/join/<%= @game.id %>/19x19#game-top">19x19 Board size</a></li>
	    </ul>
	  </div><!-- /btn-group -->
	</div><!-- /btn-toolbar -->
</div><!-- /debug-menu -->
<% end %>

app/views/games/_game.html.erb
    <tr class="<%= dom_id(game) %>">
      <td><%= game.id %></td>
      <td><%= game.horiz_user ? game.horiz_user.name : "Open" %></td>
      <td><%= game.vert_user ? game.vert_user.name : "Open" %></td>
      <td><%= game.board_width %>x<%= game.board_height %></td>
      <td><%= link_to "Join", join_game_path(game.id), dimensions: '11x11' %></td>
      <td><%= link_to "Delete", game, method: :delete, remote: true %></td>
    </tr>

app/views/games/create.js.erb
$('#games tbody').append("<%= escape_javascript(render @game) %>");
$('#<%= dom_id(@game) %>').effect('highlight');

app/views/games/destroy.js.erb
$('.<%= dom_id(@game) %>').fadeOut();

app/views/games/index.html.erb
<p id="game-top">
  <b>Games:</b>
</p>
<%= form_for(Game.new, remote: true) do |f| %>
  <%= select_tag(:dimensions, options_for_select([['11x11', 11], ['13x13', 13], ['14x14', 14], ['19x19', 19]]), { :class => 'dimensions_dropdown' }) %>
  <%= f.submit "Create Game", :class => "btn" %>
<% end %>

<table class="table table-condensed table-bordered table-hover games-table" id="games">
  <thead>
    <tr>
      <th>Game id</th>
      <th>Player 1</th>
      <th>Player 2</th>
      <th>Dimensions</th>
      <th>Join</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody>
    <%= render @games %>
  </tbody>

</table>

app/views/games/new.html.erb
<p id="game-top">
  <b>Games:</b>
</p>

<%= form_for @game, :remote => true do |f| %>
  <button class="btn" type="submit">
    Create Game
  </button>
<% end %>

<table class="table table-condensed table-bordered table-hover">
  <thead>
    <tr>
      <th>Game id</th>
      <th>Player 1</th>
      <th>Player 2</th>
      <th>Join</th>
    </tr>
  </thead>
  <tbody>
    <%= render @games %>
  </tbody>

</table>

app/views/games/show.html.erb
<p id="game-top">
  <b>Game:</b>
</p>

<canvas id="hexmap" width="700" height="500"></canvas>

<script>
	var csrf_token = $("meta[name='csrf-token']").attr("content");
  initGame(<%= @game.board_width %>, <%= @game.board_height %>, <%= current_user.id %>, <%= @game.horiz_user_id %>);
</script>

<%= session[:game_id] %>

<% if false %>
  <%= link_to 'Edit', edit_session_path(@session) %> |
  <%= link_to 'Back', sessions_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hex</title>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= favicon_link_tag "/favicon.ico" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

	<link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,900' rel='stylesheet' type='text/css'>

</head>
<body>
	<div class="container">
    <div class="row">
      <div class="span12">
        <%= render 'shared/user_header' %>

      </div>
    </div>
    <div class="row">
      <div class="span9">
        <div class="hero">
          <h1>
            <span class="logo">
              <%= link_to(image_tag("ruby.jpeg", :size => "50x50", :border => 0), root_path, :class => "btn btn-link") %>
            </span>
            Playing Hex
          </h1>
        </div>
        <%= render 'games/debug-menu' %>

        <%= render :partial => "shared/flash_messages", :locals => {:flash => flash} %>
        <%= yield %>
      </div>
      <div class="span1"></div>
      <div class="span2">
        <span class="pull-left john">
          <%= image_tag "John.png", :size => "100x50"%>
        </span>
        <span class="desc">
          <h3>About Hex</h3>
          <p>
            Hex is a strategy board game played on a hexagonal grid,
            theoretically of any size and several possible shapes,
            but traditionally as an 11×11 rhombus.
            <b>John Nash</b> (one of the game's inventors)
            advocated 14×14 as the optimal size.
          </p></span>
      </div>
    </div>
	</div>
</body>
</html>

app/views/shared/_flash_messages.html.haml
- flash.each do |type, message|
  .alert{:class => "#{twitterized_type(type)}"}
    %button{:class => "close", :data => {:dismiss => "alert"}}
      x
    - if type == :error && (flash[:error].kind_of?(ActiveModel::Errors))
      The following errors occurred:
      %br
      - message.messages.each do |key, value|
        = "#{key} #{value}"
        %br
    - else
      = message

app/views/shared/_user_header.html.erb
<div id="user_header">
  <% if current_user %>
    Logged in as <%= current_user.name %>.
    <%= link_to "Log Out", logout_path %>
  <% else %>
    <%= button_to "Guest login", users_path, method: :post %>
    <%= link_to "Sign Up", signup_path %> or
    <%= link_to "Log In", login_path %>
  <% end %>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :last_signed_in %><br />
    <%= f.datetime_select :last_signed_in %>
  </div>
  <div class="field">
    <%= f.label :password_digest %><br />
    <%= f.text_field :password_digest %>
  </div>
  <div class="field">
    <%= f.label :guest %><br />
    <%= f.check_box :guest %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>